import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

const root=new URL('../',import.meta.url).pathname;
const youtube=JSON.parse(await readFile(join(root,'data/public/youtube.json'),'utf8'));
const videos=Array.isArray(youtube.videos)?youtube.videos:[];
for(const script of ['build.mjs','build-news.mjs','build-policy-pages.mjs','build-sources-page.mjs','build-public-sections.mjs','build-channel-pages.mjs','build-media-pages.mjs','build-youtube-pages.mjs','build-guide.mjs','build-global-search.mjs'])execFileSync(process.execPath,[join(root,'scripts',script)],{stdio:'inherit'});
const ruIndex=JSON.parse(await readFile(join(root,'_site/assets/search/ru.json'),'utf8'));
const enIndex=JSON.parse(await readFile(join(root,'_site/assets/search/en.json'),'utf8'));
assert.equal(ruIndex.filter(x=>x.t==='guide').length,7);
assert.equal(enIndex.filter(x=>x.t==='guide').length,7);
assert.equal(ruIndex.filter(x=>x.t==='media').length,126);
assert.equal(ruIndex.filter(x=>x.t==='telegram').length,9);
assert.equal(ruIndex.filter(x=>x.t==='video').length,videos.length);
assert.equal(enIndex.filter(x=>x.t==='media').length,126);
const guide=ruIndex.find(x=>x.t==='guide'&&x.u==='/guide/political-prisoner/');
assert.ok(guide&&guide.n.includes('политзаключ'));
const zerkalo=ruIndex.find(x=>x.n==='Zerkalo');
assert.ok(zerkalo);
assert.equal(zerkalo.u,'/media/zerkalo/');
const eva=ruIndex.find(x=>x.d==='@evanews25');
assert.ok(eva && eva.u==='/channels/evanews25/');
if(videos.length){const current=videos[0];const video=ruIndex.find(x=>x.t==='video'&&x.u===`/videos/${current.video_id}/`);assert.ok(video);assert.equal(video.n,current.title);}
for(const item of ruIndex)assert.deepEqual(Object.keys(item).sort(),['d','n','q','t','u']);
const page=await readFile(join(root,'_site/search/index.html'),'utf8');
const home=await readFile(join(root,'_site/index.html'),'utf8');
const js=await readFile(join(root,'_site/assets/js/global-search.js'),'utf8');
assert.ok(page.includes('/assets/js/global-search.js'));
assert.ok(page.includes('/assets/search/ru.json'));
assert.ok(page.includes('data-search-type="guide"'));
assert.ok(home.includes('action="/search/"'));
assert.ok(!/https?:\/\//.test(js));
console.log(`GLOBAL_SEARCH_TEST=PASS entries=${ruIndex.length} guide=7 media=126 telegram=9 videos=${videos.length} third_party_requests=ZERO`);
