import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeJson, writeText } from './lib/fs.mjs';
import { layout, route, esc } from './templates.mjs';

const root=fileURLToPath(new URL('../',import.meta.url));
const out=join(root,'_site');
const langs=['ru','be','en','pl'];

const COPY={
 ru:{
  hubTitle:'Справочник по политическим репрессиям в Беларуси',
  hubIntro:'Практический справочник CHUDO объясняет, как читать правозащитные данные: что означает статус политзаключённого, какие события важно фиксировать при задержании и суде, как отслеживать место заключения, освобождение и качество источников.',
  disclaimer:'Справочник предназначен для правозащитного информирования и документирования. Он не заменяет индивидуальную юридическую помощь.',
  topics:{
   'political-prisoner':{title:'Кто такой политзаключённый и как CHUDO показывает этот статус',description:'Почему статус политзаключённого нельзя выводить автоматически из новости и как на CHUDO сохраняется происхождение правозащитной квалификации.',sections:[['Статус — это не ключевое слово','Упоминание человека в новости, обвинение по уголовной статье, задержание на акции или сообщение Telegram сами по себе не дают CHUDO основания назвать человека политзаключённым. На сайте статус должен иметь явное происхождение: правозащитную квалификацию конкретного источника либо отдельное редакционное решение CHUDO по утверждённой методологии.'],['Почему важно указывать источник квалификации','Формулировка «признан политзаключённым по данным…» показывает читателю, кто именно сделал правозащитный вывод. Это позволяет отличить исходную квалификацию от пересказа СМИ, автоматически собранной новости и собственного вывода CHUDO.'],['Статус может меняться, история остаётся','Освобождение, пересмотр дела или изменение правозащитной оценки не должны стирать предыдущую историю. Карточка человека хранит события во времени: когда статус был опубликован, на каком основании и что изменилось позже.'],['Что проверять на карточке','Смотрите не только текущую метку, но и дату обновления, источник статуса, связанные судебные решения, последнее известное место заключения и историю исправлений.']],check:['Есть ли конкретный источник статуса?','Понятна ли дата, к которой относится статус?','Не смешан ли статус с одной новостью или Telegram-постом?','Сохраняется ли история последующих изменений?']},
   'detention':{title:'Задержание: какие сведения важны для документирования',description:'Как отличать подтверждённое задержание от неподтверждённого сообщения и какие данные нужны для полезной правозащитной хронологии.',sections:[['Фиксируйте событие, а не только итог','Для хронологии важны дата и по возможности время задержания, место, обстоятельства, орган или подразделение, которое упоминается источником, а также ссылка на первичное сообщение. Если часть сведений неизвестна, это лучше оставить неизвестным, чем достраивать по догадке.'],['Первое сообщение может быть неполным','В первые часы информация часто меняется: человек может не выходить на связь, родственники могут не знать место нахождения, разные источники называют разные учреждения. CHUDO должен сохранять уровень уверенности и не превращать предположение в подтверждённый факт.'],['Повторное задержание — отдельное событие','Если человек был освобождён и задержан снова, новая дата не заменяет предыдущую. Каждое задержание хранится отдельным событием, чтобы история преследования не сжималась в одну строку.'],['Чувствительные данные требуют осторожности','Не следует публиковать частные номера телефонов, домашние адреса родственников, документы личности и другие данные, которые не нужны для общественного понимания события и могут увеличить риск.']],check:['Есть ли дата и источник задержания?','Понятно ли, подтверждено ли место нахождения?','Отделено ли новое задержание от предыдущего?','Не опубликованы ли лишние персональные данные?']},
   'trial-sentence':{title:'Суд, обвинение и приговор: как читать карточку дела',description:'Какие элементы судебной истории нельзя смешивать и почему обвинение, решение суда и назначенное наказание должны храниться отдельно.',sections:[['Обвинение не равно приговору','Статья обвинения показывает, что вменялось человеку на определённом этапе. Приговор — отдельное судебное событие. До вступления решения в силу и после апелляции формулировки и наказание могут изменяться.'],['Судебные события должны иметь даты','Важно различать дату начала процесса, дату решения, апелляцию, пересмотр и последующие решения. Если известен только месяц или год, CHUDO хранит частичную дату без выдумывания конкретного дня.'],['Наказание хранится отдельно','Срок лишения свободы, ограничение свободы, штраф и иные меры не должны смешиваться в одном свободном текстовом поле. Структурированная запись позволяет затем строить статистику без ручного пересчёта.'],['Имена должностных лиц требуют источника','Судьи, прокуроры и другие участники процесса показываются только когда их участие подтверждено публичным источником. Совпадение фамилий без контекста не является достаточной идентификацией.']],check:['Разделены ли обвинение и приговор?','Указана ли дата судебного события?','Структурировано ли наказание?','Есть ли источник для имени судьи или прокурора?']},
   'detention-places':{title:'СИЗО, тюрьма или колония: как отслеживать место заключения',description:'Почему последнее известное место заключения должно быть привязано ко времени и источнику, а старый адрес нельзя автоматически считать актуальным.',sections:[['Место заключения меняется','После задержания человек может пройти через ИВС, СИЗО, этапирование, колонию, тюрьму или другое учреждение. Поэтому карточка хранит последовательность размещений, а не одно вечное поле «где находится».'],['Последнее известное — не то же самое, что подтверждённое сейчас','Если нового подтверждения давно нет, CHUDO должен показывать дату последнего источника. Это особенно важно для писем, передач и публикаций, где устаревший адрес может ввести человека в заблуждение.'],['Перевод — отдельное событие','Сообщение о переводе не стирает предыдущее учреждение. Оно закрывает старый интервал и создаёт новый, сохраняя хронологию перемещений.'],['Справочник учреждений связан с карточками людей','Количество людей по учреждению должно рассчитываться из того же опубликованного snapshot, что и персональные карточки. Так сайт избегает разных цифр на разных страницах.']],check:['Есть ли дата последнего подтверждения?','Сохраняется ли предыдущая история размещений?','Не выдан ли старый адрес за актуальный?','Совпадает ли статистика учреждения с тем же snapshot?']},
   'release':{title:'Освобождение: что меняется в правозащитной карточке',description:'Почему освобождение не удаляет историю преследования и какие события важно зафиксировать после выхода человека из заключения.',sections:[['Освобождение — событие, а не удаление записи','После выхода человека его карточка не должна исчезать. Меняется текущий статус, но остаются задержания, судебные решения, срок, места заключения и источники.'],['Дата и основание должны быть отделены','Полезно фиксировать подтверждённую дату освобождения и, когда это публично известно, основание: окончание срока, помилование, изменение меры пресечения, обмен или другое событие. Если основание не подтверждено, его нельзя достраивать по слухам.'],['Бывший политзаключённый — отдельная категория отображения','Историческая квалификация может сохраняться, но человек не должен одновременно увеличивать счётчик тех, кто находится в заключении сейчас. Именно поэтому CHUDO разделяет текущих и бывших политзаключённых.'],['После освобождения могут быть новые события','Эмиграция, повторное задержание, новые дела или существенные публичные заявления фиксируются отдельно, если они относятся к правозащитной хронологии и имеют достаточное подтверждение.']],check:['Есть ли подтверждённая дата освобождения?','Не исчезла ли предыдущая история дела?','Исключён ли человек из текущего счётчика заключённых?','Не добавлено ли неподтверждённое основание освобождения?']},
   'verification':{title:'Как CHUDO проверяет данные и конфликты источников',description:'Принципы проверки происхождения фактов, работы с противоречиями, датами, исправлениями и автоматическими лентами источников.',sections:[['Источник не равен факту','Каждая публикация — это сообщение конкретного источника. CHUDO сохраняет происхождение и только после отдельной проверки может использовать сообщение для изменения канонической записи человека.'],['Несколько перепечаток не дают несколько подтверждений','Если десять сайтов перепечатали одну исходную новость, это по-прежнему одна цепочка происхождения. При оценке подтверждений важно искать независимые первичные или действительно самостоятельные источники.'],['Противоречие нельзя скрывать','Если источники расходятся по дате, месту заключения, сроку или личности, система должна сохранить конфликт и остановить автоматическое продвижение спорного факта. Уверенный ответ не создаётся искусственно.'],['Исправления имеют историю','Существенный факт может быть исправлен, отозван, заменён или помечен спорным. Новая версия не должна делать вид, что предыдущая публикация никогда не существовала.'],['Автоматические ленты ограничены','RSS, Telegram и YouTube помогают быстро обнаруживать материалы, но не имеют права автоматически присваивать правозащитный статус или переписывать каноническую карточку человека.']],check:['Известно ли происхождение каждого существенного факта?','Независимы ли подтверждающие источники?','Есть ли явный конфликт между источниками?','Сохраняется ли история исправлений?','Не превратилась ли автоматическая лента в автоматический вердикт?']}
  },
  checklist:'Короткая проверка',related:'Связанные разделы',back:'ВЕСЬ СПРАВОЧНИК',methodology:'МЕТОДОЛОГИЯ CHUDO',sources:'ИСТОЧНИКИ',corrections:'ИСПРАВЛЕНИЯ'
 },
 be:{
  hubTitle:'Даведнік па палітычных рэпрэсіях у Беларусі',hubIntro:'Практычны даведнік CHUDO тлумачыць, як чытаць праваабарончыя даныя: статус палітвязня, затрыманне, суд, месца зняволення, вызваленне і праверку крыніц.',disclaimer:'Даведнік прызначаны для праваабарончага інфармавання і дакументавання і не замяняе індывідуальную юрыдычную дапамогу.',
  topics:{
   'political-prisoner':{title:'Хто такі палітвязень і як CHUDO паказвае гэты статус',description:'Статус не выводзіцца аўтаматычна з навіны: CHUDO захоўвае паходжанне праваабарончай кваліфікацыі.',sections:[['Статус — не ключавое слова','Навіна, артыкул абвінавачання або паведамленне Telegram самі па сабе не даюць падставы аўтаматычна назваць чалавека палітвязнем. Патрэбная выразна названая праваабарончая крыніца або асобнае рэдакцыйнае рашэнне паводле метадалогіі.'],['Паходжанне кваліфікацыі павінна быць бачным','Чытач павінен разумець, хто менавіта прызнаў чалавека палітвязнем і на якую дату адносіцца гэты статус.'],['Гісторыя не выдаляецца','Вызваленне або змяненне ацэнкі не сцірае папярэднія падзеі. Картка захоўвае храналогію.'],['Глядзіце шырэй за адну метку','Правярайце крыніцу статусу, дату, судовыя рашэнні, месца зняволення і гісторыю выпраўленняў.']],check:['Ёсць канкрэтная крыніца статусу?','Зразумелая дата статусу?','Статус не пабудаваны на адной навіне?','Захавана гісторыя змен?']},
   'detention':{title:'Затрыманне: што важна дакументаваць',description:'Як аддзяляць пацверджанае затрыманне ад непацверджанага паведамлення і што захоўваць у храналогіі.',sections:[['Фіксуйце падзею','Важныя дата, месца, абставіны, названая крыніцай структура і спасылка на першаснае паведамленне. Невядомыя даныя лепш пакінуць невядомымі.'],['Першае паведамленне можа быць няпоўным','У першыя гадзіны месца знаходжання можа быць невядома. CHUDO не ператварае здагадку ў пацверджаны факт.'],['Паўторнае затрыманне — новая падзея','Новая дата не замяняе старую. Кожнае затрыманне захоўваецца асобна.'],['Лішнія персанальныя даныя не патрэбныя','Прыватныя тэлефоны, хатнія адрасы і дакументы не павінны публікавацца без неабходнасці.']],check:['Ёсць дата і крыніца?','Пацверджана месца?','Паўторнае затрыманне асобнае?','Няма лішніх персанальных даных?']},
   'trial-sentence':{title:'Суд, абвінавачанне і прысуд',description:'Чаму абвінавачанне, судовае рашэнне і пакаранне трэба захоўваць як асобныя элементы.',sections:[['Абвінавачанне не роўнае прысуду','Артыкул абвінавачання і выніковае рашэнне суда — розныя падзеі. Пасля апеляцыі змест можа змяніцца.'],['Судовыя падзеі маюць даты','Пачатак працэсу, прысуд, апеляцыя і перагляд не павінны злівацца ў адну дату.'],['Пакаранне структуруецца','Тэрмін, штраф або іншая мера захоўваюцца асобна, каб не будаваць статыстыку з вольнага тэксту.'],['Імёны службовых асоб патрабуюць крыніцы','Суддзя або пракурор паказваецца толькі пры публічным пацверджанні ўдзелу.']],check:['Абвінавачанне і прысуд асобныя?','Ёсць дата?','Пакаранне структуравана?','Ёсць крыніца для службовай асобы?']},
   'detention-places':{title:'СІЗА, турма або калонія: як адсочваць месца зняволення',description:'Чаму апошняе вядомае месца заўсёды трэба прывязваць да даты і крыніцы.',sections:[['Месца змяняецца','Чалавек можа прайсці праз ІЧУ, СІЗА, этап і калонію. Картка захоўвае паслядоўнасць, а не адно вечнае поле.'],['Апошняе вядомае не заўсёды актуальнае','Калі свежага пацверджання няма, павінна быць бачная дата апошняй крыніцы.'],['Перавод — асобная падзея','Новае месца не сцірае папярэдняе, а працягвае храналогію.'],['Лічбы па ўстановах павінны паходзіць з аднаго snapshot','Так карткі людзей і даведнік устаноў не даюць розныя вынікі.']],check:['Ёсць дата апошняга пацверджання?','Гісторыя месцаў захавана?','Стары адрас не выдаецца за актуальны?','Лічбы з аднаго snapshot?']},
   'release':{title:'Вызваленне: што змяняецца ў картцы',description:'Вызваленне змяняе бягучы стан, але не выдаляе гісторыю пераследу.',sections:[['Запіс не выдаляецца','Пасля вызвалення застаюцца затрыманні, суды, прысуд, месцы зняволення і крыніцы.'],['Дата і падстава асобныя','Калі падстава вызвалення публічна невядомая, CHUDO не дадае яе па чутках.'],['Былы палітвязень — асобная катэгорыя','Чалавек не павінен павялічваць лік тых, хто знаходзіцца ў зняволенні цяпер.'],['Новыя падзеі дадаюцца асобна','Паўторнае затрыманне або новая справа не перапісваюць мінулае.']],check:['Ёсць дата вызвалення?','Гісторыя справы захавана?','Чалавек выключаны з бягучага ліку?','Падстава не выдумана?']},
   'verification':{title:'Як CHUDO правярае даныя і канфлікты крыніц',description:'Паходжанне фактаў, незалежнасць крыніц, супярэчнасці і гісторыя выпраўленняў.',sections:[['Крыніца не роўная факту','Публікацыя паказвае паходжанне сцвярджэння і не аўтаматычна змяняе кананічную картку.'],['Перадрукі не множаць пацверджанні','Дзесяць копій адной навіны не становяцца дзесяццю незалежнымі крыніцамі.'],['Супярэчнасці захоўваюцца','Калі крыніцы разыходзяцца, аўтаматычнае прасоўванне факта спыняецца.'],['Выпраўленні маюць гісторыю','Факт можа быць выпраўлены, адкліканы, заменены або пазначаны як спрэчны.'],['Аўтаматычныя стужкі маюць межы','RSS і Telegram дапамагаюць знаходзіць матэрыялы, але не выдаюць аўтаматычны праваабарончы вердыкт.']],check:['Паходжанне факта вядома?','Крыніцы незалежныя?','Канфлікт бачны?','Выпраўленні захаваны?','Аўтаматыка не стала вердыктам?']}
  },checklist:'Кароткая праверка',related:'Звязаныя раздзелы',back:'УВЕСЬ ДАВЕДНІК',methodology:'МЕТАДАЛОГІЯ CHUDO',sources:'КРЫНІЦЫ',corrections:'ВЫПРАЎЛЕННІ'
 },
 en:{
  hubTitle:'Guide to political repression in Belarus',hubIntro:'A practical CHUDO guide to reading human-rights data: political-prisoner designations, detention, trials, detention locations, release and source verification.',disclaimer:'This guide is for human-rights information and documentation. It is not a substitute for individual legal advice.',
  topics:{
   'political-prisoner':{title:'What political-prisoner status means on CHUDO',description:'Why CHUDO does not infer political-prisoner status automatically from a headline and how the provenance of a human-rights designation is preserved.',sections:[['A status is not a keyword','A detention, criminal charge, protest-related report or Telegram post does not by itself let CHUDO label someone a political prisoner. The designation must have explicit human-rights provenance or a separate CHUDO editorial determination under an approved methodology.'],['The source of the designation matters','Readers should be able to see who made the human-rights assessment and the date to which it applies. This separates the original designation from media rewrites and automated news feeds.'],['History remains when circumstances change','Release or a later change in assessment does not erase the earlier history. Status events remain part of the chronology.'],['Read the whole profile','Check the designation source, date, court events, latest detention location and correction history rather than relying on one badge.']],check:['Is a concrete designation source named?','Is the relevant date clear?','Is the status separated from a single news report?','Is later history preserved?']},
   'detention':{title:'Detention: what should be documented',description:'How to distinguish a confirmed detention from an early unverified report and which details make a useful chronology.',sections:[['Record the event, not just the outcome','Useful fields include date, location, circumstances, the agency named by the source and the primary-source link. Unknown details should remain unknown rather than be guessed.'],['Early reports may be incomplete','In the first hours, relatives and reporters may not know where a person is being held. CHUDO preserves uncertainty instead of promoting an assumption to fact.'],['A re-arrest is a new event','If a person is released and detained again, the new detention does not overwrite the earlier one.'],['Minimize sensitive data','Private phone numbers, relatives’ home addresses and identity documents should not be published merely because they appeared in a message.']],check:['Is there a date and source?','Is the detention location confirmed or uncertain?','Is a re-arrest stored separately?','Is unnecessary personal data excluded?']},
   'trial-sentence':{title:'Charges, trial and sentence: how to read a case record',description:'Why charges, judgments and punishment must remain distinct events rather than one free-text summary.',sections:[['A charge is not a judgment','The article charged at one stage is different from the court’s later decision. Appeals or review may change the legal outcome.'],['Court events need dates','Opening of trial, judgment, appeal and review should not collapse into a single date. Partial dates are preferable to invented precision.'],['Punishment should be structured','Imprisonment, restriction, fines or other measures are stored separately so statistics do not depend on manually reading prose.'],['Officials require attribution','Judges, prosecutors and other officials are named only when their role is supported by a public source; a matching surname is not enough.']],check:['Are charge and judgment separated?','Is the court event dated?','Is punishment structured?','Is the official’s role sourced?']},
   'detention-places':{title:'Detention centers, prisons and colonies: tracking location',description:'Why a detention location must be tied to time and source, and why an old mailing address should not be presented as current.',sections:[['Locations change','A person may move through temporary detention, pre-trial detention, transfer and a penal facility. CHUDO stores a sequence rather than one permanent “location” field.'],['Last known is not always current','If there is no recent confirmation, the date of the last source must remain visible. This matters for correspondence and public reporting.'],['Transfer is its own event','A new location does not delete the previous placement; it extends the chronology.'],['Facility counts must share one snapshot','Counts on facility pages are derived from the same published person snapshot so different sections do not contradict one another.']],check:['Is the latest confirmation dated?','Are previous placements preserved?','Is an old address clearly dated?','Do facility counts use the same snapshot?']},
   'release':{title:'Release: what changes and what must remain',description:'Why release changes the current state but does not erase the history of persecution.',sections:[['Release is an event, not deletion','Detentions, trials, sentence, facilities and sources remain part of the public record after release.'],['Date and basis are separate','Record a confirmed release date and, only when publicly supported, the basis for release. Rumor should not fill a missing field.'],['Former political prisoner is a separate display category','A historical designation may remain while the person must no longer increase the current imprisoned count.'],['Later events remain separate','Re-arrest, new proceedings or other relevant events are appended to the chronology rather than rewriting earlier history.']],check:['Is the release date confirmed?','Is prior history preserved?','Is the person removed from the current imprisoned count?','Is the basis for release sourced?']},
   'verification':{title:'How CHUDO verifies data and handles source conflicts',description:'Provenance, independent confirmation, conflicts, corrections and the boundaries of automated source feeds.',sections:[['A source is not the same as a fact','Every publication is a claim from a named source. Only a separate validation path can promote a claim into a canonical person record.'],['Rewrites are not independent confirmation','Ten outlets copying one original story still represent one provenance chain. Independent confirmation requires genuinely separate evidence.'],['Conflicts must remain visible','If sources disagree on identity, date, location or sentence, CHUDO records the conflict and blocks automatic promotion instead of inventing certainty.'],['Corrections have history','A material fact may be corrected, retracted, superseded or marked disputed without pretending the prior publication never existed.'],['Automation has boundaries','RSS, Telegram and YouTube help discovery and publication of source material but cannot automatically assign a human-rights designation or rewrite the canonical person record.']],check:['Is provenance visible?','Are confirmations genuinely independent?','Is source conflict exposed?','Is correction history preserved?','Has automation stayed within its boundary?']}
  },checklist:'Quick check',related:'Related sections',back:'FULL GUIDE',methodology:'CHUDO METHODOLOGY',sources:'SOURCES',corrections:'CORRECTIONS'
 },
 pl:{
  hubTitle:'Przewodnik po represjach politycznych na Białorusi',hubIntro:'Praktyczny przewodnik CHUDO wyjaśnia, jak czytać dane o prawach człowieka: status więźnia politycznego, zatrzymanie, proces, miejsce osadzenia, zwolnienie i weryfikację źródeł.',disclaimer:'Przewodnik służy informowaniu i dokumentowaniu praw człowieka. Nie zastępuje indywidualnej pomocy prawnej.',
  topics:{
   'political-prisoner':{title:'Co oznacza status więźnia politycznego w CHUDO',description:'Dlaczego CHUDO nie nadaje statusu automatycznie na podstawie nagłówka i jak zachowuje pochodzenie kwalifikacji organizacji praw człowieka.',sections:[['Status nie jest słowem kluczowym','Zatrzymanie, zarzut, protest lub wpis Telegram nie wystarczają, aby CHUDO automatycznie nazwało osobę więźniem politycznym. Potrzebne jest jawne źródło kwalifikacji albo odrębna decyzja redakcyjna zgodna z metodologią.'],['Źródło kwalifikacji ma znaczenie','Czytelnik powinien widzieć, kto dokonał oceny i do jakiej daty się odnosi.'],['Historia pozostaje widoczna','Zwolnienie lub późniejsza zmiana oceny nie usuwa wcześniejszych wydarzeń.'],['Czytaj cały profil','Sprawdzaj źródło statusu, datę, wydarzenia sądowe, ostatnie miejsce osadzenia i historię korekt.']],check:['Czy wskazano źródło statusu?','Czy data jest jasna?','Czy status oddzielono od pojedynczej wiadomości?','Czy zachowano historię zmian?']},
   'detention':{title:'Zatrzymanie: co warto dokumentować',description:'Jak odróżniać potwierdzone zatrzymanie od wczesnej, niezweryfikowanej informacji.',sections:[['Dokumentuj wydarzenie','Ważne są data, miejsce, okoliczności, organ wskazany przez źródło i link do pierwotnego komunikatu. Nieznane dane powinny pozostać nieznane.'],['Pierwsze informacje bywają niepełne','W pierwszych godzinach miejsce pobytu może być nieznane. CHUDO nie zamienia przypuszczenia w fakt.'],['Ponowne zatrzymanie to nowe wydarzenie','Nowa data nie zastępuje poprzedniej.'],['Minimalizuj dane wrażliwe','Prywatne telefony, adresy krewnych i dokumenty tożsamości nie powinny być publikowane bez konieczności.']],check:['Czy jest data i źródło?','Czy miejsce jest potwierdzone?','Czy ponowne zatrzymanie zapisano osobno?','Czy usunięto zbędne dane osobowe?']},
   'trial-sentence':{title:'Zarzuty, proces i wyrok',description:'Dlaczego zarzut, orzeczenie sądu i kara muszą pozostać odrębnymi elementami historii sprawy.',sections:[['Zarzut nie jest wyrokiem','Artykuł zarzutu na jednym etapie i późniejsze orzeczenie sądu to różne wydarzenia.'],['Wydarzenia sądowe potrzebują dat','Rozpoczęcie procesu, wyrok, apelacja i ponowne rozpoznanie nie powinny zlewać się w jedną datę.'],['Kara powinna być ustrukturyzowana','Pozbawienie wolności, ograniczenie, grzywna i inne środki są przechowywane osobno.'],['Urzędnicy wymagają źródła','Sędzia lub prokurator jest wskazywany tylko przy publicznym potwierdzeniu jego roli.']],check:['Czy zarzut i wyrok są oddzielone?','Czy wydarzenie ma datę?','Czy kara jest ustrukturyzowana?','Czy rola urzędnika ma źródło?']},
   'detention-places':{title:'Areszt, więzienie lub kolonia: śledzenie miejsca osadzenia',description:'Dlaczego miejsce osadzenia musi być powiązane z datą i źródłem.',sections:[['Miejsce się zmienia','Osoba może przechodzić przez kilka placówek. CHUDO przechowuje sekwencję, a nie jedno stałe pole.'],['Ostatnie znane nie zawsze znaczy aktualne','Gdy brak świeżego potwierdzenia, widoczna powinna być data ostatniego źródła.'],['Przeniesienie jest osobnym wydarzeniem','Nowa placówka nie usuwa poprzedniej.'],['Liczby placówek pochodzą z jednego snapshotu','Dzięki temu katalog placówek i profile osób nie pokazują sprzecznych liczb.']],check:['Czy ostatnie potwierdzenie ma datę?','Czy zachowano wcześniejsze miejsca?','Czy stary adres nie jest przedstawiany jako aktualny?','Czy liczby pochodzą z jednego snapshotu?']},
   'release':{title:'Zwolnienie: co się zmienia, a co pozostaje',description:'Dlaczego zwolnienie zmienia stan bieżący, ale nie usuwa historii represji.',sections:[['Zwolnienie to wydarzenie, nie usunięcie','Zatrzymania, proces, kara, miejsca osadzenia i źródła pozostają w historii.'],['Data i podstawa są odrębne','Podstawę zwolnienia podaje się tylko wtedy, gdy ma publiczne potwierdzenie.'],['Były więzień polityczny to odrębna kategoria','Osoba nie może nadal zwiększać liczby osób przebywających obecnie w więzieniu.'],['Późniejsze wydarzenia dopisuje się osobno','Ponowne zatrzymanie lub nowe postępowanie nie nadpisuje wcześniejszej historii.']],check:['Czy data zwolnienia jest potwierdzona?','Czy zachowano wcześniejszą historię?','Czy osoba została usunięta z bieżącego licznika?','Czy podstawa zwolnienia ma źródło?']},
   'verification':{title:'Jak CHUDO weryfikuje dane i konflikty źródeł',description:'Pochodzenie faktów, niezależność potwierdzeń, sprzeczności i historia korekt.',sections:[['Źródło nie jest tym samym co fakt','Publikacja pozostaje twierdzeniem wskazanego źródła, dopóki osobny proces nie dopuści jej do kanonicznego profilu.'],['Przedruki nie mnożą potwierdzeń','Wiele kopii jednej wiadomości nadal stanowi jeden łańcuch pochodzenia.'],['Sprzeczności muszą być widoczne','Gdy źródła różnią się co do osoby, daty, miejsca lub kary, automatyczna promocja faktu zostaje zatrzymana.'],['Korekty mają historię','Fakt może zostać poprawiony, wycofany, zastąpiony lub oznaczony jako sporny.'],['Automatyzacja ma granice','RSS i Telegram pomagają znajdować materiały, ale nie nadają automatycznie kwalifikacji praw człowieka.']],check:['Czy pochodzenie jest widoczne?','Czy potwierdzenia są niezależne?','Czy konflikt źródeł jest pokazany?','Czy historia korekt została zachowana?','Czy automatyzacja pozostała ograniczona?']}
  },checklist:'Krótka kontrola',related:'Powiązane sekcje',back:'CAŁY PRZEWODNIK',methodology:'METODOLOGIA CHUDO',sources:'ŹRÓDŁA',corrections:'KOREKTY'
 }
};

function outputPath(lang,path){const prefix=lang==='ru'?'':lang;const clean=path.replace(/^\//,'').replace(/\/$/,'');return join(out,prefix,clean,'index.html');}
function searchText(value=''){return String(value).toLocaleLowerCase('ru').normalize('NFKD').replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
function topicPath(slug){return `/guide/${slug}/`;}
function links(lang,c){return `<div class="quick-links"><a class="secondary-btn" href="${route(lang,'/guide/')}">${esc(c.back)}</a><a class="secondary-btn" href="${route(lang,'/methodology/')}">${esc(c.methodology)}</a><a class="secondary-btn" href="${route(lang,'/sources/')}">${esc(c.sources)}</a><a class="secondary-btn" href="${route(lang,'/corrections/')}">${esc(c.corrections)}</a></div>`;}
function hubBody(lang,c){return `<article class="container page guide-page"><p class="eyebrow">CHUDO HUMAN RIGHTS CENTER · GUIDE</p><h1>${esc(c.hubTitle)}</h1><p class="catalog-note">${esc(c.hubIntro)}</p><div class="news-grid">${Object.entries(c.topics).map(([slug,topic])=>`<article class="tech-news-card"><h2><a href="${route(lang,topicPath(slug))}">${esc(topic.title)}</a></h2><p>${esc(topic.description)}</p><a class="text-link" href="${route(lang,topicPath(slug))}">→</a></article>`).join('')}</div><section class="profile-section"><p><strong>${esc(c.disclaimer)}</strong></p></section><div class="quick-links"><a class="secondary-btn" href="${route(lang,'/methodology/')}">${esc(c.methodology)}</a><a class="secondary-btn" href="${route(lang,'/transparency/')}">CHUDO TRUST</a></div></article>`;}
function topicBody(lang,c,slug,topic){const related=Object.entries(c.topics).filter(([key])=>key!==slug).slice(0,3);return `<article class="container page guide-page"><p class="eyebrow">CHUDO HUMAN RIGHTS CENTER · GUIDE</p><h1>${esc(topic.title)}</h1><p class="catalog-note">${esc(topic.description)}</p>${topic.sections.map(([title,text])=>`<section class="profile-section"><h2>${esc(title)}</h2><p>${esc(text)}</p></section>`).join('')}<section class="profile-section"><h2>${esc(c.checklist)}</h2><ul>${topic.check.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="profile-section"><h2>${esc(c.related)}</h2><div class="quick-links">${related.map(([key,item])=>`<a class="secondary-btn" href="${route(lang,topicPath(key))}">${esc(item.title)}</a>`).join('')}</div></section><p class="catalog-note">${esc(c.disclaimer)}</p>${links(lang,c)}</article>`;}

for(const lang of langs){
  const c=COPY[lang];
  await writeText(outputPath(lang,'/guide/'),layout({lang,title:c.hubTitle,description:c.hubIntro,path:'/guide/',body:hubBody(lang,c)}));
  const search=[];
  for(const [slug,topic] of Object.entries(c.topics)){
    await writeText(outputPath(lang,topicPath(slug)),layout({lang,title:topic.title,description:topic.description,path:topicPath(slug),body:topicBody(lang,c,slug,topic)}));
    search.push({t:'guide',n:topic.title,d:topic.description,u:route(lang,topicPath(slug)),q:searchText(`${topic.title} ${topic.description} ${topic.sections.flat().join(' ')}`)});
  }
  search.unshift({t:'guide',n:c.hubTitle,d:c.hubIntro,u:route(lang,'/guide/'),q:searchText(`${c.hubTitle} ${c.hubIntro}`)});
  await writeJson(join(out,'assets','guide-index',`${lang}.json`),search);
}
console.log(`GUIDE_BUILD=PASS locales=4 pages=${langs.length*(1+Object.keys(COPY.ru.topics).length)} topics=${Object.keys(COPY.ru.topics).length} search_records=${langs.length*(1+Object.keys(COPY.ru.topics).length)}`);
